### ISSUE TITLE
1024 byte mdr?

### ISSUE THREAD

**Issue by Its-Vichy** [billythegoat356/Rufus#3]
`sock.send(b'Rufus Here -> https://github.com/billythegoat356/Rufus\n'*1024)`, C'est pas parce que tu duplique 1024 fois t'a string que t'a 1024 bytes..

Ton script ne sert clairement à rien, tu va jamais DoS avec des ports 1GBs tu down rien avec :,
Juste à regarder les statistiques, tu envoie 50MBs mdr ? mais t'en reçois 1GBs la tu t'auto-down. (sauf si c'est la machine victime mais ça ne change pas les choses tu reçois que 1gbs), entre autre tu va juste te taper un firewall qui va drop tous tes packets tu peux à peine hit un home..

On est en 2022 si tu souhaite faire mal il faut décentraliser ton attaque, a part pondre un script uselless en python qui utilise ton processeur à fond ya rien qui va tu aurais pu au moin le faire en C :,

Bref je comprend pas ton vieux tool, tu vien insulter les skript kiddie qui font les pro ddos alors qu'ils ne savent pas manier un shell mais tu dev un script qui est au même niveaux :,,

Et je te vois d'avance à supprimer mon issue mais dans ce cas tu ne feras que valider ce que je dis,
bref bonne soirée et arrête de sauter une ligne sûr deux ça fait déguelasse et les global aussi c'est moche

**Comment by jaimeleschatii** [comment]
real

**Comment by billythegoat356** [comment]
Avec mon script j'ai réussi à down mon site en tapant du 1GBPS. C'est une attaque DOS basique en Python, c'est pas ouf mais ça fonctionne.

**Comment by billythegoat356** [comment]
Je suis pas ouf en réseau, j'ai juste voulu dev un script pour faire des petites attaques DOS avec mes compétences en réseau.

Si tu n'as rien d'autre à dire, tu peux close.
Je suis pas une merde à empêcher les autres de donner leurs avis sur mes progs.
